### ISSUE TITLE
process finished with exit code -1073741819 (0xc0000005)

### ISSUE THREAD

**Issue by happywind-boy** [vanandrew/brainextractor#4]
When I run BrainExtractor， sometimes the process stops suddenly with this：

process finished with exit code -1073741819 (0xc0000005)

How can I fix it？ And what caused it？ 

Thanks！

**Comment by vanandrew** [comment]
It's difficult to debug this without additional context. What data are you trying to run? Are there any messages before/after the error (this may help me figure out at what stage the process failed).

Other information that may help:
- Python version
- Operating System
- Parameters you are running `Brainextractor` with

**Comment by happywind-boy** [comment]
Sorry， there is no message before/after this error.  I tried BET on data collection UCSF-PDGM which can be found on TCIA.

I use Python 3.7 and Windows 10， and the iteration of BET is set to 800.  I found if the iteration is set to 300, this error disappeared. So this is caused by insufficient computer memory? 

Thanks！

**Comment by vanandrew** [comment]
I've only tested brainextractor on Linux based systems, and ensuring this works on Windows is just something I currently don't have the bandwidth for.

Try running this on Linux and if you get the same issue, feel free to report back here.

**Comment by happywind-boy** [comment]
Thanks!

**Comment by happywind-boy** [comment]
Now I see Linux is OK. Maybe my PC is not good enough......
