### ISSUE TITLE
Need help on using Longitudinal MRI image as input 

### ISSUE THREAD

**Issue by JinqianPan** [vanandrew/brainextractor#5]
Hi,

I am working on skull-stripping for brain scan. I have cross-sectional and longitudinal MRI brain scans data. When I use cross-sectional data, the brainextractor shows good result. However, the brainextractor shows bad in longitudinal data.

<img width="988" alt="image" src="https://github.com/vanandrew/brainextractor/assets/60722953/ee9386e0-d0a6-4f60-be0c-11d6031c3673">
<img width="993" alt="image" src="https://github.com/vanandrew/brainextractor/assets/60722953/e81ebdf2-3f41-4391-b33f-19cb527c8bb7">

When I start the brainextractor for longitudinal data, it shows `UserWarning: The voxels in this image are non-isotropic!                 Brain extraction settings may not be valid!`. So I view the **pixdim** in header, I get `[-1.     1.     1.     2.     6.002  0.     0.     0.   ]`.

What should I do for the python code when using brainextractor?

Thanks!

**Comment by vanandrew** [comment]
Based on your pixdim, it looks like your voxels are isotropic. I think the first dim being negative is throwing the check off. So it should be fine to ignore.

Regarding the quality of the skull strip, you can try play around with the settings to see if you can get a better result?

But in my judgement, you should probably just try using the actual FSL bet tool to do the skull stripping for the particular dataset you're showing me here.  It has many more features, such as ability to clean up the neck and eyes, that might be confusing the brain surface growing, so you actually might get better results that way. (Note this library was originally developed for a class project, and I only implemented the very basics of skull stripping that the actual FSL bet tool implements).

**Comment by JinqianPan** [comment]
Thank you very much! I will try it!
