### ISSUE TITLE
Python stops unexpectedly

### ISSUE THREAD

**Issue by ajayhakkumar** [vanandrew/brainextractor#8]
$ brainextractor pp01_mp2rage_whole_brain_t1_std_defaced.nii.gz 1.nii.gz
Initializing...
Parameters: bt=0.500000, d1=20.000000, d2=10.000000, rmin=3.330000, rmax=10.000000
tmin: 0.000000, t2: 0.000000, t: 312.700000, t98: 3127.000000, tmax: 3999.000000
Center-of-Mass: [115.63921706 142.84159284 172.89465062]
Head Radius: 161.157240
Median within Head Radius: 1692.000000
Initializing surface...
Brain extractor initialization complete!
Running surface deformation...
Segmentation fault: 11

**Comment by vanandrew** [comment]
Please resubmit this issue using the following template:

```
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Version [e.g. 22]
 - Python Version

**Additional context**
Add any other context about the problem here.
```
